gem 'smart_proxy_dynflow', :path => '../smart_proxy_dynflow'
gem 'smart_proxy_dynflow_core', :path => '../smart_proxy_dynflow'
gem 'smart_proxy_remote_execution_ssh', :path => '../smart_proxy_remote_execution_ssh'
gem 'foreman_remote_execution_core', :path => '../foreman_remote_execution'
gem 'ed25519'
gem 'bcrypt_pbkdf'
